name: Unit Test

on:
  push:

jobs:
  unit:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Test
        run: |
          npm install
          make test
